### PR TITLE
Refactoring of HLS code generator

### PR DESCRIPTION
**Pull request by dillonhuff**
@jeffsetter this PR includes some refactoring to clean up the HLS code generator. It only touches the new code generator files. LMK if you see any issues with it so I can merge it.

### CODE REVIEW

**Comment by dillonhuff** [comment]
@jeffsetter also I changed the build script to use the master branch of GarnetFlow as the docker build environment, it was previously set to use a branch of GarnetFlow that has been merged to master.

**Review by jeffsetter — APPROVED** [review]
lgtm

**Comment by jeffsetter** [comment]
I don't expect these changes to affect garnetflow, but in the future it's also best to kick off a run of garnetflow with the new branch.

**Comment by dillonhuff** [comment]
@jeffsetter that makes sense, how do trigger garnetflow with a new branch?

**Comment by jeffsetter** [comment]
Right now I think it is manual, but if you're willing to do some scripting, an extension to 
   https://github.com/StanfordAHA/GarnetFlow/blob/master/scripts/python_repo.py
for Halide-to-Hardware, we could have something done automatically. Keyi and Teguh might have ideas about this.

**Comment by dillonhuff** [comment]
Ahh I see. We should definitely talk with those two about it.

**Pull request merged**
