### PR TITLE
Ub rewrite joey

### PR DESCRIPTION
**Pull request by joyliu37**

### CODE REVIEW

**Comment by dillonhuff** [comment]
@joyliu37 it seems that the conv_3_3 unit test is failing. Could you revert to the old conv_3_3 and push that so we can get this thing merged?

**Comment by joyliu37** [comment]
I revert to the old 3x3 conv image size, but it broke at another app ushift and report coreIR error. Any idea what cause this error? @dillonhuff

**Comment by joyliu37** [comment]
Can you double check this PR if there is an issue. @dillonhuff

**Review by dillonhuff — APPROVED** [review]

**Comment by dillonhuff** [comment]
@joyliu37 looks great!

**Pull request merged**
