### PR TITLE
Update to use with lakelib and new mapper

### PR DESCRIPTION
**Pull request by norabarlow**

### CODE REVIEW

**Comment by norabarlow** [comment]
The updated mapper works with the old code generator that produces line buffers (not unified buffers), as well as with unified buffers.

**Comment by dillonhuff** [comment]
@norabarlow thats great!

Have you tried running the hardware unit tests on your machine by doing:

```bash
./test/scripts/hw_unit_tests.sh 
```

The travis build says that they are failing.

**Comment by norabarlow** [comment]
@dillonhuff it's complaining about `ERROR: Missing namespace: lakelib`, which I'm not sure how to fix. I've tried linking lakelib in the Makefile, which I pushed, but it doesn't work.

**Comment by joyliu37** [comment]
Dillon's merged_hw_unit test is not using unified buffer, but just linebuffer. However, `lakelib.linebuffer` is just a copy paste from `commonlib.linebuffer` which should not result issue. 
Is the complaint about `missing namespace: lakelib` point to any line of any file?

**Comment by norabarlow** [comment]
@joyliu37 the errors point to somewhere inside the compiled library files, so unfortunately I can't get line numbers. I tried modifying the tests to load lakelib but it didn't work.

**Comment by norabarlow** [comment]
Hmm...not sure how to fix this GarnetFlow error.

**Comment by leonardt** [comment]
I just found about the error, looks like a regression from a recent magma change.  Pushed a hot fix and re-running the builds now

**Comment by leonardt** [comment]
New build is running here: https://buildkite.com/stanford-aha/garnetflow/builds/1325#e0d053eb-f3ee-401b-85bc-6f91ebf62c5b but it seems like you may need to push a commit here to trigger the GitHub integration to update with a new build status

**Comment by leonardt** [comment]
Nevermind, looks like it's now updated the build result, passing: https://buildkite.com/stanford-aha/garnetflow/builds/1325#e0d053eb-f3ee-401b-85bc-6f91ebf62c5b

**Review by dillonhuff — APPROVED** [review]
Looks good to me

**Pull request merged**
