### PR TITLE
Hls codegen with hardware buffers merge

### PR DESCRIPTION
**Pull request by dillonhuff**
This pull request brings together the Jeff's unified buffer branch (hwbuffer_jeff), with the latest HLS code generator (which was recently merged with master).

### CODE REVIEW

**Comment by jeffsetter** [comment]
I know this has little to do with your changes, but could you help me remove some of the printouts during the execution? It's a bit hard to read the logs as is.

**Comment by dillonhuff** [comment]
@jeffsetter sure. Is there any particular file where you want to remove things? ExtractHWBuffers seems to be a particularly bad offender for excessive logging IMO.

**Comment by jeffsetter** [comment]
Yea, the major offenders will be my files (ExtractHWBuffers and InsertHWBuffers). You could remove every printout to std::cout in there.

**Comment by dillonhuff** [comment]
@jeffsetter just deleted a bunch of printouts. If that is the only issue could you approve this PR so that we can merge? The other printouts can be dealt with in another PR, and I think we should get in the habit of making many smaller pull requests anyway.

**Review by jeffsetter — APPROVED** [review]
Looks good. Now the old codegen can run with the new unified buffer in progress.

**Pull request merged**
