### PR TITLE
HLS based code generation

### PR DESCRIPTION
**Pull request by dillonhuff**
@jeffsetter as promised here is a giant pull request with the new code generator, new unit tests, and delay insertion logic.

I'm sure we will need a bunch of changes, but the build passes for me on Travis.

LMK what you think.

### CODE REVIEW

**Comment by dillonhuff** [comment]
@jeffsetter I have reintroduced warnings as errors and reverted to the old coreir code generator.

Could you review this PR so that the final checks can be run?

**Comment by jeffsetter** [comment]
The extra tests that I don't run on travis are essentially going through the test folder and doing `make compare` to ensure none of the unit tests are broken.

**Comment by dillonhuff** [comment]
@jeffsetter in that case, if you are ok with this merge could you confirm your reviewed status on github? The reviewers tab says this pull request is awaiting review by you and the "Travis CI - Branch" checks have not run yet as a result.

**Comment by jeffsetter** [comment]
I believe the "Travis CI - branch" checks are just the .travis.yml running on your account. However, it should be the same as the pull request run, so that should be fine.

**Review by jeffsetter — APPROVED** [review]
Code looks good to me.

**Pull request merged**
